# server
server.port=${SERVER_PORT:8080}
# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# logging
logging.level.root=INFO
logging.level.com.avinashee0012.zorvyn=INFO
logging.level.org.hibernate.SQL=OFF
logging.file.name=/var/log/zorvyn/zorvyn.log