# server
server.port=8080
# MySQL database for dev
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# jpa setting for mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# swagger
swagger.server-url=${SWAGGER_SERVER_URL}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# logging
logging.level.root=INFO
logging.level.com.avinashee0012.zorvyn=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.file.name=logs/zorvyn-dev.log