# server
server.port=8081
# H2 database for testing
spring.datasource.url=jdbc:h2:mem:zorvyn_test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# jpa setting for h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
# swagger
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# logging
logging.level.root=WARN
logging.level.com.avinashee0012.zorvyn=INFO
logging.file.name=logs/zorvyn-test.log